---
baseURL: "http://tour-guide-john-17380.netlify.com/"
languageCode: "en-us"
title: "I Am Simme"
theme: "simme"
pygmentsuseclasses: true
PygmentsCodeFences: true
permalinks:
      post: "/:title"
metaFataFormat: "yaml"
paginate: 10
paginatePath: "page"
titlecaseStyle: "AP"
copyright: "This work is licensed under the MIT license."
author:
   name: "Simon Ljungberg"
rssLimit: 20
outputFormats:
   jsonfeed:
      mediaType: "application/json"
      baseName: "feed"
      isPlaintext: true
outputs:
   home:
      - "rss"
      - "html"
      - "jsonfeed"
canonifyurls: true
...
